linters:
  enable:
    - errcheck
    - gci
    - gosec
    - gosimple
    - govet
    - ineffassign
    - revive
    - staticcheck
    - typecheck
    - unused

linters-settings:
  gci:
    sections:
    - standard
    - default
    - prefix(github.com/leonhfr/honeybadger)

issues:
  include:
    - EXC0005
    - EXC0012
    - EXC0014
    - EXC0015
