name: CI

on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          cache: true
          go-version-file: go.mod

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Test
        run: go test -v ./...

      - name: Build
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --snapshot --rm-dist

  release:
    needs: checks
    if: startsWith(github.event.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          cache: true
          go-version-file: go.mod

      - name: Release
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: release
    if: startsWith(github.event.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Raspberry Pi
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.BOT_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/leonhfr/honeybadger-bot/actions/workflows/binary.yml/dispatches \
            -d '{"ref": "master"}'
